[package]
name = "aperture"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
os-integration = ["dep:aperture-os"]
cellguard = ["dep:aperture-cellguard"]

[dependencies]
aperture-artifacts = { workspace = true }
aperture-auth = { workspace = true }
aperture-cellguard = { workspace = true, optional = true }
aperture-events = { workspace = true }
aperture-http = { workspace = true }
aperture-os = { workspace = true, optional = true }
aperture-runtime = { workspace = true }
aperture-settings = { workspace = true }
aperture-storage = { workspace = true }
aperture-tasks = { workspace = true }

anyhow = { workspace = true, features = ["std"] }
clap = { workspace = true, features = ["std", "derive", "env", "help", "usage", "error-context", "suggestions"] }
hex = { workspace = true, features = ["alloc"] }
jiff = { workspace = true, features = ["std"] }
rustls = { workspace = true, features = ["ring"] }
serde = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs", "sync", "time", "signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "ansi", "tracing-log"] }
uuid = { workspace = true, features = ["std", "v4"] }
