[package]
name = "aperture-storage"
version = "0.1.0"
description = "Aperture storage layer."
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
jiff = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
thiserror = { workspace = true, features = ["std"] }
tracing = { workspace = true, features = ["std", "attributes"] }
turso = { workspace = true, features = ["fts"] }
uuid = { workspace = true, features = ["std"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
