[package]
name = "aperture-storage"
version.workspace = true
description = "Aperture storage layer."
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
aperture-runtime = { workspace = true }
hex = { workspace = true, features = ["alloc"] }
jiff = { workspace = true, features = ["std", "serde"] }
password-hash = { workspace = true, features = ["alloc", "std"] }
serde = { workspace = true, features = ["std", "derive"] }
serde_json = { workspace = true, features = ["std"] }
subtle = { workspace = true }
thiserror = { workspace = true, features = ["std"] }
tracing = { workspace = true, features = ["std", "attributes"] }
turso = { workspace = true, features = ["fts"] }
utoipa = { workspace = true, features = ["macros", "jiff_0_2"] }
uuid = { workspace = true, features = ["std"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
