[workspace]
resolver = "3"
members = [
    "aperture",
    "aperture-artifacts",
    "aperture-auth",
    "aperture-http",
    "aperture-storage",
    "aperture-tasks",
]

[workspace.package]
authors = ["Simon Berger <simon@siku2.io>"]
edition = "2024"
license = "AGPL-3.0-or-later"
publish = false
repository = "https://github.com/stargrid-systems/aperture"
rust-version = "1.93"

[workspace.dependencies]
aperture-artifacts = { version = "0.1.0", path = "aperture-artifacts" }
aperture-auth = { version = "0.1.0", path = "aperture-auth" }
aperture-http = { version = "0.1.0", path = "aperture-http" }
aperture-storage = { version = "0.1.0", path = "aperture-storage" }
aperture-tasks = { version = "0.1.0", path = "aperture-tasks" }

anyhow = { version = "1", default-features = false }
argon2 = { version = "0.5", default-features = false }
async-trait = { version = "0.1", default-features = false }
axum = { version = "0.8", default-features = false }
backhand = { version = "0.25", default-features = false }
bytes = { version = "1", default-features = false }
casbin = { version = "2.20", default-features = false }
clap = { version = "4", default-features = false }
cookie = { version = "0.18", default-features = false }
futures-util = { version = "0.3", default-features = false }
jiff = { version = "0.2", default-features = false }
mime_guess = { version = "2", default-features = false }
miette = { version = "7", default-features = false }
oci-client = { version = "0.17", default-features = false }
password-hash = { version = "0.5", default-features = false }
rand = { version = "0.9", default-features = false }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
sha2 = { version = "0.11", default-features = false }
subtle = { version = "2", default-features = false }
thiserror = { version = "2", default-features = false }
tokio = { version = "1", default-features = false }
tokio-stream = { version = "0.1", default-features = false }
tokio-util = { version = "0.7", default-features = false }
tower = { version = "0.5", default-features = false }
tracing = { version = "0.1", default-features = false }
tower-http = { version = "0.7", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
turso = { version = "0.6", default-features = false }
uuid = { version = "1", default-features = false }
utoipa = { version = "5", default-features = false }
utoipa-axum = { version = "0.2", default-features = false }

[workspace.lints.clippy]
absolute_paths = "warn"
