//! SVG serializer. Walks the canvas element tree and streams markup
//! byte-for-byte compatible with `DiceBear`'s `Renderer` for default options,
//! without allocating.
//!
//! Output order is `<defs>` (encountered during the body walk: literal defs
//! like masks and gradients, plus component variant bodies, nested components
//! first) followed by the clipped body: the background and the canvas tree,
//! with visible components as `<use>` references.
//! Because `<defs>` must precede the body but is discovered while walking it,
//! the renderer makes two deterministic passes: variant selection is fully
//! keyed by `(seed, key)`, so recomputing it is safe.

use core::fmt::Write;
use core::{fmt, ptr};

use crate::color::Rgb8;
use crate::data::{AttrVal, ComponentDef, Node, Range, VariantDef};
use crate::number::{Num, equals};
use crate::prng::{Prng, hash_u32};
use crate::{Animation, Style};

const MAX_DEFS: usize = 32;

struct Escaped<'a>(&'a str);

/// Renders an optional resolved color, or nothing. Used for the background
/// rect: upstream omits the `fill` attribute when the style defines no
/// background palette.
struct Rgb8Display(Option<Rgb8>);

impl fmt::Display for Rgb8Display {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            Some(color) => write!(f, "{color}"),
            None => Ok(()),
        }
    }
}

impl fmt::Display for Escaped<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for ch in self.0.chars() {
            match ch {
                '&' => f.write_str("&amp;")?,
                '\'' => f.write_str("&apos;")?,
                '"' => f.write_str("&quot;")?,
                '<' => f.write_str("&lt;")?,
                '>' => f.write_str("&gt;")?,
                other => f.write_char(other)?,
            }
        }
        Ok(())
    }
}

/// Tracks which `<defs>` entries have been emitted. Literal defs (children of
/// `defs` elements) dedupe by their `id` attribute; component defs by
/// component pointer plus variant name, which is what the formatted def id is
/// derived from.
struct DefSink<'a> {
    seen_ids: [&'a str; MAX_DEFS],
    id_count: usize,
    seen_comps: [(*const ComponentDef<'a>, &'a str); MAX_DEFS],
    comp_count: usize,
}

impl<'a> DefSink<'a> {
    const fn new() -> Self {
        Self {
            seen_ids: [""; MAX_DEFS],
            id_count: 0,
            seen_comps: [(ptr::null(), ""); MAX_DEFS],
            comp_count: 0,
        }
    }

    fn saw_id(&self, id: &'a str) -> bool {
        self.seen_ids[..self.id_count].contains(&id)
    }

    fn push_id(&mut self, id: &'a str) {
        debug_assert!(self.id_count < MAX_DEFS, "too many defs");
        self.seen_ids[self.id_count] = id;
        self.id_count += 1;
    }

    fn saw_comp(&self, component: &ComponentDef<'a>, variant: &str) -> bool {
        self.seen_comps[..self.comp_count]
            .iter()
            .any(|&(ptr_, name)| ptr::eq(ptr_, component) && name == variant)
    }

    fn push_comp(&mut self, component: &ComponentDef<'a>, variant: &'a str) {
        debug_assert!(self.comp_count < MAX_DEFS, "too many defs");
        self.seen_comps[self.comp_count] = (component, variant);
        self.comp_count += 1;
    }
}

pub fn render(
    f: &mut fmt::Formatter<'_>,
    style: &Style<'_>,
    seed: &str,
    animation: Animation,
) -> fmt::Result {
    let prng = Prng::new(seed);
    let hash = hash_u32(style.source_name, seed);

    write!(
        f,
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 {w} {h}\" fill=\"none\" \
         shape-rendering=\"auto\" aria-hidden=\"true\">",
        w = Num(style.canvas_w),
        h = Num(style.canvas_h)
    )?;
    write!(
        f,
        "<!-- Generated by DiceBear (https://www.dicebear.com) -->{metadata}<defs>",
        metadata = style.metadata
    )?;

    // Pass 1: emit defs in body-walk encounter order. A component's def comes
    // after the defs of everything nested inside its variant.
    let mut sink = DefSink::new();
    walk_defs(f, &prng, style, &style.canvas, animation, hash, &mut sink)?;

    write!(
        f,
        "<clipPath id=\"clip-{hash:08x}\"><rect width=\"{w}\" height=\"{h}\" rx=\"0\" \
         ry=\"0\"/></clipPath></defs>",
        w = Num(style.canvas_w),
        h = Num(style.canvas_h)
    )?;

    let background = style
        .color("background")
        .map(|color| prng.resolve(style, color));
    write!(
        f,
        "<g clip-path=\"url(#clip-{hash:08x})\"><rect width=\"{w}\" height=\"{h}\" fill=\"{bg}\"/>",
        w = Num(style.canvas_w),
        h = Num(style.canvas_h),
        bg = Rgb8Display(background)
    )?;

    // Pass 2: emit the body tree (visible components become <use> references).
    for node in style.canvas.iter() {
        write_node(f, &prng, style, node, animation, hash)?;
    }

    f.write_str("</g></svg>")
}

/// Pass 1: diverts literal defs and registers component defs, nested
/// components first (post-order).
fn walk_defs<'a>(
    f: &mut fmt::Formatter<'_>,
    prng: &Prng<'_>,
    style: &Style<'a>,
    nodes: &[Node<'a>],
    animation: Animation,
    hash: u32,
    sink: &mut DefSink<'a>,
) -> fmt::Result {
    for node in nodes {
        match node {
            Node::El {
                name: "defs",
                children,
                ..
            } => {
                for child in *children {
                    if let Some(id) = node_id(child) {
                        if sink.saw_id(id) {
                            continue;
                        }
                        sink.push_id(id);
                    }
                    write_node(f, prng, style, child, animation, hash)?;
                }
            }
            Node::El { children, .. } => {
                walk_defs(f, prng, style, children, animation, hash, sink)?;
            }
            Node::Component {
                name, component, ..
            } => {
                if let Some(variant) = prng.variant(name, component, animation)
                    && !sink.saw_comp(component, variant.name)
                {
                    walk_defs(f, prng, style, variant.elements, animation, hash, sink)?;
                    sink.push_comp(component, variant.name);
                    write_def(f, prng, style, component.name, variant, animation, hash)?;
                }
            }
            Node::Text { .. } => {}
        }
    }
    Ok(())
}

fn write_def(
    f: &mut fmt::Formatter<'_>,
    prng: &Prng<'_>,
    style: &Style<'_>,
    source: &str,
    variant: &VariantDef<'_>,
    animation: Animation,
    hash: u32,
) -> fmt::Result {
    write!(
        f,
        "<g id=\"{source}-{name}-{hash:08x}\">",
        name = variant.name
    )?;
    for el in variant.elements {
        write_node(f, prng, style, el, animation, hash)?;
    }
    f.write_str("</g>")
}

fn write_node(
    f: &mut fmt::Formatter<'_>,
    prng: &Prng<'_>,
    style: &Style<'_>,
    node: &Node<'_>,
    animation: Animation,
    hash: u32,
) -> fmt::Result {
    match node {
        Node::El { name: "defs", .. } => Ok(()),
        Node::El {
            name,
            attrs,
            children,
        } => {
            write!(f, "<{name}")?;
            for (key, value) in *attrs {
                match value {
                    AttrVal::Lit(s) => write!(f, " {key}=\"{v}\"", key = key, v = Escaped(s))?,
                    AttrVal::Color(color) => {
                        write!(f, " {key}=\"{}\"", prng.resolve(style, color))?;
                    }
                }
            }
            if children.is_empty() {
                f.write_str("/>")
            } else {
                f.write_str(">")?;
                for child in *children {
                    write_node(f, prng, style, child, animation, hash)?;
                }
                write!(f, "</{name}>")
            }
        }
        Node::Text { value } => write!(f, "{}", Escaped(value)),
        Node::Component {
            name,
            component,
            attrs,
        } => {
            if let Some(variant) = prng.variant(name, component, animation) {
                write_use(f, prng, name, component, attrs, variant, hash)?;
            }
            Ok(())
        }
    }
}

/// Emits the `<use>` reference for a visible component: the user transform
/// (placement) first, then the style's translate and rotate inside it.
fn write_use<'a>(
    f: &mut fmt::Formatter<'_>,
    prng: &Prng<'_>,
    name: &str,
    component: &'a ComponentDef<'a>,
    attrs: &'a [(&'a str, AttrVal<'a>)],
    variant: &VariantDef<'a>,
    hash: u32,
) -> fmt::Result {
    let rotate = component.rotate.map_or(0.0, |Range(min, max)| {
        prng.float(&[name, "Rotate"], min, max)
    });
    let translate_x = component.translate.map_or(0.0, |(Range(min, max), _)| {
        prng.float(&[name, "TranslateX"], min, max)
    });
    let translate_y = component.translate.map_or(0.0, |(_, Range(min, max))| {
        prng.float(&[name, "TranslateY"], min, max)
    });

    let width = component.width.unwrap_or(0.0);
    let height = component.height.unwrap_or(0.0);
    let user_transform = lit_attr(attrs, "transform");

    let has_translate = !equals(translate_x, 0.0) || !equals(translate_y, 0.0);
    let has_rotate = !equals(rotate, 0.0);

    f.write_str("<use")?;
    if user_transform.is_some() || has_translate || has_rotate {
        f.write_str(" transform=\"")?;
        let mut wrote = if let Some(ut) = user_transform {
            f.write_str(ut)?;
            true
        } else {
            false
        };
        if has_translate {
            if wrote {
                f.write_str(" ")?;
            }
            write!(
                f,
                "translate({x}, {y})",
                x = Num(translate_x / 100.0 * width),
                y = Num(translate_y / 100.0 * height)
            )?;
            wrote = true;
        }
        if has_rotate {
            if wrote {
                f.write_str(" ")?;
            }
            write!(
                f,
                "rotate({a}, {cx}, {cy})",
                a = Num(rotate),
                cx = Num(width / 2.0),
                cy = Num(height / 2.0)
            )?;
        }
        f.write_str("\"")?;
    }
    write!(
        f,
        " href=\"#{source}-{variant_name}-{hash:08x}\"/>",
        source = component.name,
        variant_name = variant.name
    )
}

fn node_id<'a>(node: &Node<'a>) -> Option<&'a str> {
    let Node::El { attrs, .. } = node else {
        return None;
    };
    lit_attr(attrs, "id")
}

fn lit_attr<'a>(attrs: &'a [(&'a str, AttrVal<'a>)], key: &str) -> Option<&'a str> {
    attrs.iter().find_map(|(k, v)| match v {
        AttrVal::Lit(s) if *k == key => Some(*s),
        _ => None,
    })
}
