//! SVG serializer. Walks the canvas element tree and streams markup
//! byte-for-byte compatible with `DiceBear`'s `Renderer` for default options,
//! without allocating.
//!
//! Output order is `<defs>` (component variant bodies deduped, then the
//! clipPath) followed by the clipped body (background plus `<use>` references).
//! Because `<defs>` must precede the body but is discovered while walking it,
//! the renderer makes two deterministic passes: variant selection is fully
//! keyed by `(seed, key)`, so recomputing it is safe.

use core::{fmt, ptr};

use crate::Style;
use crate::data::{AttrVal, Node, VariantDef};
use crate::number::{Num, equals};
use crate::prng::hash_u32;
use crate::resolver::Resolver;
use crate::svg::{Escaped, ScaleAtPoint, UseElement};

/// Maximum canvas nodes across `DiceBear` styles.
const MAX_CANVAS: usize = 32;
/// Maximum gradient ids across `DiceBear` styles.
const MAX_GRADIENTS: usize = 4;

pub struct Renderer<'a> {
    style: &'a Style<'a>,
    seed: &'a str,
}

impl<'a> Renderer<'a> {
    pub const fn new(style: &'a Style<'a>, seed: &'a str) -> Self {
        Self { style, seed }
    }

    #[expect(clippy::too_many_arguments, reason = "rendering parameters")]
    fn write_def<'b>(
        &self,
        f: &mut fmt::Formatter<'_>,
        resolver: &Resolver<'_>,
        source: &str,
        variant: &VariantDef<'b>,
        hash: u32,
        seen_grad: &mut [&'b str],
        grad_count: &mut usize,
    ) -> fmt::Result {
        self.divert_defs(f, resolver, variant.elements, seen_grad, grad_count)?;

        write!(
            f,
            "<g id=\"{source}-{name}-{hash:08x}\">",
            source = source,
            name = variant.name,
            hash = hash
        )?;
        for el in variant.elements {
            self.write_node(f, resolver, el)?;
        }
        f.write_str("</g>")
    }

    #[expect(clippy::self_only_used_in_recursion, reason = "tree walk")]
    fn write_node(
        &self,
        f: &mut fmt::Formatter<'_>,
        resolver: &Resolver<'_>,
        node: &Node<'_>,
    ) -> fmt::Result {
        match node {
            Node::El { name, .. } if *name == "defs" => Ok(()),
            Node::El {
                name,
                attrs,
                children,
            } => {
                write!(f, "<{name}")?;
                for (key, value) in *attrs {
                    match value {
                        AttrVal::Lit(s) => write!(f, " {key}=\"{v}\"", key = key, v = Escaped(s))?,
                        AttrVal::Color(color) => {
                            if let Some(resolved) = resolver.color(color) {
                                write!(f, " {key}=\"{v}\"", key = key, v = Escaped(resolved))?;
                            }
                        }
                    }
                }
                if children.is_empty() {
                    f.write_str("/>")
                } else {
                    f.write_str(">")?;
                    for child in *children {
                        self.write_node(f, resolver, child)?;
                    }
                    write!(f, "</{name}>")
                }
            }
            Node::Component { .. } => Ok(()),
        }
    }

    fn divert_defs<'b>(
        &self,
        f: &mut fmt::Formatter<'_>,
        resolver: &Resolver<'_>,
        nodes: &[Node<'b>],
        seen_grad: &mut [&'b str],
        grad_count: &mut usize,
    ) -> fmt::Result {
        for node in nodes {
            if let Node::El {
                name: "defs",
                children,
                ..
            } = node
            {
                for child in *children {
                    if let Some(id) = node_id(child) {
                        if seen_grad[..*grad_count].contains(&id) {
                            continue;
                        }
                        debug_assert!(*grad_count < MAX_GRADIENTS, "too many gradients");
                        seen_grad[*grad_count] = id;
                        *grad_count += 1;
                    }
                    self.write_node(f, resolver, child)?;
                }
            } else if let Node::El { children, .. } = node {
                self.divert_defs(f, resolver, children, seen_grad, grad_count)?;
            }
        }
        Ok(())
    }
}

#[expect(clippy::too_many_lines, reason = "two-pass SVG renderer")]
impl fmt::Display for Renderer<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let resolver = Resolver::new(self.seed);
        let hash = hash_u32(self.style.source_name, self.seed);

        write!(
            f,
            "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 {w} {h}\" fill=\"none\" \
             shape-rendering=\"auto\" aria-hidden=\"true\">",
            w = Num(self.style.canvas_w),
            h = Num(self.style.canvas_h)
        )?;
        write!(
            f,
            "<!-- Generated by DiceBear (https://www.dicebear.com) -->{metadata}<defs>",
            metadata = self.style.metadata
        )?;

        // Pre-compute variants for all canvas nodes (reused in both passes).
        let mut variants: [Option<&VariantDef>; MAX_CANVAS] = [None; MAX_CANVAS];
        for (i, node) in self.style.canvas.iter().enumerate() {
            if let Node::Component {
                name, component, ..
            } = node
            {
                variants[i] = resolver.variant(name, component);
            }
        }

        let mut seen_grad: [&str; MAX_GRADIENTS] = [""; MAX_GRADIENTS];
        let mut grad_count: usize = 0;

        // Pass 1: emit unique defs. Dedup by component pointer + variant name.
        for (i, node) in self.style.canvas.iter().enumerate() {
            let Some(variant) = variants[i] else {
                continue;
            };
            let Node::Component { component, .. } = node else {
                continue;
            };

            let is_dup = self
                .style
                .canvas
                .iter()
                .take(i)
                .enumerate()
                .any(|(j, earlier)| {
                    let Node::Component { component: ec, .. } = earlier else {
                        return false;
                    };
                    variants[j]
                        .is_some_and(|ev| ptr::eq(*ec, *component) && ev.name == variant.name)
                });

            if is_dup {
                continue;
            }

            self.write_def(
                f,
                &resolver,
                component.name,
                variant,
                hash,
                &mut seen_grad,
                &mut grad_count,
            )?;
        }

        // clipPath
        write!(
            f,
            "<clipPath id=\"clip-{hash:08x}\"><rect width=\"{w}\" height=\"{h}\" rx=\"0\" \
             ry=\"0\"/></clipPath></defs>",
            w = Num(self.style.canvas_w),
            h = Num(self.style.canvas_h)
        )?;

        // Background
        let bg = resolver.color(&self.style.background).unwrap_or("");
        write!(
            f,
            "<g clip-path=\"url(#clip-{hash:08x})\"><rect width=\"{w}\" height=\"{h}\" \
             fill=\"{bg}\"/>",
            w = Num(self.style.canvas_w),
            h = Num(self.style.canvas_h),
            bg = Escaped(bg)
        )?;

        // Pass 2: emit <use> per visible component.
        for (i, node) in self.style.canvas.iter().enumerate() {
            let Some(variant) = variants[i] else {
                continue;
            };
            let Node::Component {
                name,
                component,
                attrs,
            } = node
            else {
                continue;
            };

            let transform = resolver.component_transform(name, component);
            let width = component.width.unwrap_or(0.0);
            let height = component.height.unwrap_or(0.0);
            let cx = width / 2.0;
            let cy = height / 2.0;

            let user_transform = attrs.iter().find_map(|(k, v)| match (*k, v) {
                ("transform", AttrVal::Lit(s)) => Some(*s),
                _ => None,
            });

            let use_el = UseElement {
                source: component.name,
                variant_name: variant.name,
                hash,
                user_transform,
                translate: (!equals(transform.translate_x, 0.0)
                    || !equals(transform.translate_y, 0.0))
                .then(|| {
                    (
                        transform.translate_x / 100.0 * width,
                        transform.translate_y / 100.0 * height,
                    )
                }),
                rotate: (!equals(transform.rotate, 0.0)).then_some((transform.rotate, cx, cy)),
                scale: (!equals(transform.scale, 1.0)).then_some(ScaleAtPoint {
                    scale: transform.scale,
                    cx,
                    cy,
                }),
            };
            write!(f, "{use_el}")?;
        }

        f.write_str("</g></svg>")
    }
}

fn node_id<'a>(node: &Node<'a>) -> Option<&'a str> {
    let Node::El { attrs, .. } = node else {
        return None;
    };
    attrs.iter().find_map(|(k, v)| match (*k, v) {
        ("id", AttrVal::Lit(s)) => Some(*s),
        _ => None,
    })
}
