[package]
name = "dicebear-lite"
version = "0.1.0"
description = "Slim, byte-compatible DiceBear constellation avatar renderer."
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true
