[package]
name = "aperture-http"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
aperture-artifacts = { workspace = true }
aperture-core = { workspace = true }
anyhow = { workspace = true, features = ["std"] }
axum = { workspace = true, features = ["json"] }
backhand = { workspace = true, features = ["gzip", "zstd"] }
jiff = { workspace = true, features = ["std", "serde"] }
mime_guess = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
tokio = { workspace = true, features = ["rt", "sync"] }
tokio-stream = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true, features = ["macros", "axum_extras", "jiff_0_2"] }
utoipa-axum = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
